name: PR Checks
on: [pull_request]
jobs:
  block-wip-pr:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Block WIP PR
      uses: samholmes/block-wip-pr-action@v1.1.0
