# Priority: Critical
# Test ID: C000026
# Title: Exchange settings
# Expected Result:
#   1. Exchange settings (from within Settings scene) are visible andfunctional



appId: ${MAESTRO_APP_ID}
tags:
- all
- C000026
---
- runFlow:
    file: ../common/launch-cleared.yaml
- runFlow:
    file: ../common/login-password.yaml
    env:
      USERNAME: ${MAESTRO_EDGE_UTXO_USERNAME}
      PASSWORD: ${MAESTRO_EDGE_UTXO_PASSWORD}
- runFlow:
    file: ../common/dismiss-modals.yaml

- tapOn: "Exchange Settings"